# Generated by Django 4.2.7 on 2023-11-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbalance',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
